name: ultimatePaintOff
version: '1.0'
main: org.cws.ultimatePaintOff.UltimatePaintOff
api-version: '1.19'
commands:
    poarsenal:
        description: Open Arsenal Inventory
        permission: op
    poqueue:
        description: join queue
        permission: op
    poleave:
        description: Leave Queue/game
        permission: op
    postart:
        description: Start game
        permission: op
    poinfo:
      description: Show queue info
      permission: op
    poarena:
      description: Set arena positions
      permission: op
    postop:
      description: Stop game
      permission: op
